In [1]:
import pandas as pd

In [8]:
data = {'name' : ['sudh' , 'krish' , 'hitesh' , 'tulesko'],
        'salary' : [100 , 200 , 300 , 400],
        'mail_id' : ['sudh@ineuron.ai' , 'krish@ineuron.ai' , 'hitesh@ineuron.ai' , 'tulesko@ineuron.ai'],
        'addr' : ['blr' , 'blr' , 'blr' , 'mum']
    }

In [11]:
pd.DataFrame(data)

name  salary             mail_id addr
0     sudh     100     sudh@ineuron.ai  blr
1    krish     200    krish@ineuron.ai  blr
2   hitesh     300   hitesh@ineuron.ai  blr
3  tulesko     400  tulesko@ineuron.ai  mum

In [14]:
df =pd.DataFrame(data,index = [4,5,6,7])

In [15]:
df.loc[5:6]

name  salary            mail_id addr
5   krish     200   krish@ineuron.ai  blr
6  hitesh     300  hitesh@ineuron.ai  blr

In [16]:
df.iloc[5:6]


Empty DataFrame
Columns: [name, salary, mail_id, addr]
Index: []

In [18]:
df.iloc[1:3]

name  salary            mail_id addr
5   krish     200   krish@ineuron.ai  blr
6  hitesh     300  hitesh@ineuron.ai  blr

In [19]:
df =pd.DataFrame(data,index = ["sudh","krish","hitesh","telusko"])

In [20]:
df

name  salary             mail_id addr
sudh        sudh     100     sudh@ineuron.ai  blr
krish      krish     200    krish@ineuron.ai  blr
hitesh    hitesh     300   hitesh@ineuron.ai  blr
telusko  tulesko     400  tulesko@ineuron.ai  mum

In [21]:
df =pd.DataFrame(data,index = [0,1,3,4])

In [22]:
df

name  salary             mail_id addr
0     sudh     100     sudh@ineuron.ai  blr
1    krish     200    krish@ineuron.ai  blr
3   hitesh     300   hitesh@ineuron.ai  blr
4  tulesko     400  tulesko@ineuron.ai  mum

In [30]:
data1= {'pf_nu' : [234,45,54465,656],
        'income_tax' : [234,565,767,6778],
        'mobile_no' : [23543,43543,454,5656],
        'courses' : ['ds' , 'bigdata' , 'web dev ' , 'blockchian']
    
}

In [31]:
df1=pd.DataFrame(data1)

In [32]:
df1

pf_nu  income_tax  mobile_no     courses
0    234         234      23543          ds
1     45         565      43543     bigdata
2  54465         767        454    web dev 
3    656        6778       5656  blockchian

In [33]:
pd.concat([df,df1])
# by dfault axis = 0

name  salary             mail_id addr    pf_nu  income_tax  mobile_no  \
0     sudh   100.0     sudh@ineuron.ai  blr      NaN         NaN        NaN   
1    krish   200.0    krish@ineuron.ai  blr      NaN         NaN        NaN   
3   hitesh   300.0   hitesh@ineuron.ai  blr      NaN         NaN        NaN   
4  tulesko   400.0  tulesko@ineuron.ai  mum      NaN         NaN        NaN   
0      NaN     NaN                 NaN  NaN    234.0       234.0    23543.0   
1      NaN     NaN                 NaN  NaN     45.0       565.0    43543.0   
2      NaN     NaN                 NaN  NaN  54465.0       767.0      454.0   
3      NaN     NaN                 NaN  NaN    656.0      6778.0     5656.0   

      courses  
0         NaN  
1         NaN  
3         NaN  
4         NaN  
0          ds  
1     bigdata  
2    web dev   
3  blockchian

In [34]:
pd.concat([df,df1],axis =1)

name  salary             mail_id addr    pf_nu  income_tax  mobile_no  \
0     sudh   100.0     sudh@ineuron.ai  blr    234.0       234.0    23543.0   
1    krish   200.0    krish@ineuron.ai  blr     45.0       565.0    43543.0   
2      NaN     NaN                 NaN  NaN  54465.0       767.0      454.0   
3   hitesh   300.0   hitesh@ineuron.ai  blr    656.0      6778.0     5656.0   
4  tulesko   400.0  tulesko@ineuron.ai  mum      NaN         NaN        NaN   

      courses  
0          ds  
1     bigdata  
2    web dev   
3  blockchian  
4         NaN

In [44]:
data2 = {'0' : ['sudh' , 'krish' , 'hitesh' , 'tulesko'],
        '1' : [100 , 200 , 300 , 400],
        '2' : ['sudh@ineuron.ai' , 'krish@ineuron.ai' , 'hitesh@ineuron.ai' , 'tulesko@ineuron.ai'],
        '3' : ['blr' , 'blr' , 'blr' , 'mum']
    }

In [45]:
data3= {'0' : [234,45,54465,656],
        '1' : [234,565,767,6778],
        '2' : [23543,43543,454,5656],
        '3' : ['ds' , 'bigdata' , 'web dev ' , 'blockchian']
    
}

In [49]:
df2 = pd.DataFrame(data2)
df2

0    1                   2    3
0     sudh  100     sudh@ineuron.ai  blr
1    krish  200    krish@ineuron.ai  blr
2   hitesh  300   hitesh@ineuron.ai  blr
3  tulesko  400  tulesko@ineuron.ai  mum

In [50]:
df3 = pd.DataFrame(data3)
df3

0     1      2           3
0    234   234  23543          ds
1     45   565  43543     bigdata
2  54465   767    454    web dev 
3    656  6778   5656  blockchian

In [51]:
pd.concat([df2,df3])

0     1                   2           3
0     sudh   100     sudh@ineuron.ai         blr
1    krish   200    krish@ineuron.ai         blr
2   hitesh   300   hitesh@ineuron.ai         blr
3  tulesko   400  tulesko@ineuron.ai         mum
0      234   234               23543          ds
1       45   565               43543     bigdata
2    54465   767                 454    web dev 
3      656  6778                5656  blockchian

In [68]:
data4 = {'emp_id' : [101,102,103,104],
         'salary' : [234, 345,200,400],
         'pf' : [23,34,56,78],
         }
         

In [69]:
data5  = {'emp_id' : [101,102,104,105],
          'mob_no' : [3434,5656,767,878],
          'house_nu' : [345,345,345,56]
    
}

In [58]:
df4 =pd.DataFrame(data4)

In [59]:
df4

emp_id  salary  pf
0     101     234  23
1     102     345  34
2     103     200  56
3     104     400  78

In [60]:
df5 = pd.DataFrame(data5)

In [61]:
df5

emp_id  mob_no  house_nu
0     101    3434       345
1     102    5656       345
2     104     767       345
3     105     878        56

In [62]:
pd.merge(df4,df5)

emp_id  salary  pf  mob_no  house_nu
0     101     234  23    3434       345
1     102     345  34    5656       345
2     104     400  78     767       345

In [63]:
pd.merge(df4,df5,how ='left')

emp_id  salary  pf  mob_no  house_nu
0     101     234  23  3434.0     345.0
1     102     345  34  5656.0     345.0
2     103     200  56     NaN       NaN
3     104     400  78   767.0     345.0

In [64]:
pd.merge(df4,df5,how ='right')

emp_id  salary    pf  mob_no  house_nu
0     101   234.0  23.0    3434       345
1     102   345.0  34.0    5656       345
2     104   400.0  78.0     767       345
3     105     NaN   NaN     878        56

In [65]:
pd.merge(df4,df5,how = "right",on = "emp_id")

emp_id  salary    pf  mob_no  house_nu
0     101   234.0  23.0    3434       345
1     102   345.0  34.0    5656       345
2     104   400.0  78.0     767       345
3     105     NaN   NaN     878        56

In [70]:
data6 = {'emp_id1' : [101,102,103,104],
         'salary' : [234, 345,200,400],
         'pf' : [23,34,56,78],
         }
         
data7  = {'emp_id2' : [101,102,104,105],
          'mob_no' : [3434,5656,767,878],
          'house_nu' : [345,345,345,56]
    
}

In [72]:
df6 =pd.DataFrame(data6)
df6

emp_id1  salary  pf
0      101     234  23
1      102     345  34
2      103     200  56
3      104     400  78

In [73]:
df7 =pd.DataFrame(data7)
df7

emp_id2  mob_no  house_nu
0      101    3434       345
1      102    5656       345
2      104     767       345
3      105     878        56

In [75]:
pd.merge(df6,df7)

#No common columns to perform merge on. Merge options: left_on=None, right_on=None, left_index=False, right_index=False


MergeError: No common columns to perform merge on. Merge options: left_on=None, right_on=None, left_index=False, right_index=False

In [78]:
pd.merge(df6,df7,left_on="emp_id1",right_on = "emp_id2",how = "inner")


emp_id1  salary  pf  emp_id2  mob_no  house_nu
0      101     234  23      101    3434       345
1      102     345  34      102    5656       345
2      104     400  78      104     767       345

In [92]:
data8 = {'emp_id' : [101,102,103,104],
         'salary' : [234, 345,200,400],
         'pf' : [23,34,56,78],
         }
         
data9  = {'emp_id' : [101,102,104,105,88],
          'salary' : [234, 345,200,400,889],
          'house_nu' : [345,345,345,56,897]
    
}

In [93]:
df8= pd.DataFrame(data8)

In [94]:
df8

emp_id  salary  pf
0     101     234  23
1     102     345  34
2     103     200  56
3     104     400  78

In [95]:
df9 = pd.DataFrame(data9)
df9

emp_id  salary  house_nu
0     101     234       345
1     102     345       345
2     104     200       345
3     105     400        56
4      88     889       897

In [96]:
pd.merge(df8,df9)

emp_id  salary  pf  house_nu
0     101     234  23       345
1     102     345  34       345

In [97]:
pd.merge(df8,df9,on=['emp_id','salary'])
#emp_id and salary must have common value

emp_id  salary  pf  house_nu
0     101     234  23       345
1     102     345  34       345

In [103]:
data10 = {'emp_id1' : [101,102,103,104],
         'salary1' : [234, 345,200,400],
         'pf' : [23,34,56,78],
         }
         
data11  = {'emp_id2' : [101,102,104,105,88],
          'salary2' : [234, 345,200,400,889],
          'house_nu' : [345,345,345,56,897]
    
}

In [104]:
df10 = pd.DataFrame(data10,index =['a','b','c','d'])
df10

emp_id1  salary1  pf
a      101      234  23
b      102      345  34
c      103      200  56
d      104      400  78

In [105]:
df11 = pd.DataFrame(data11,index =['a','b','d','e','f'])
df11

emp_id2  salary2  house_nu
a      101      234       345
b      102      345       345
d      104      200       345
e      105      400        56
f       88      889       897

In [106]:
df10.join(df11)

emp_id1  salary1  pf  emp_id2  salary2  house_nu
a      101      234  23    101.0    234.0     345.0
b      102      345  34    102.0    345.0     345.0
c      103      200  56      NaN      NaN       NaN
d      104      400  78    104.0    200.0     345.0

In [110]:
df_sales=pd.read_csv(r'C:\Users\soume\data fsds\sales_data_final.csv')
df_sales

order_id  order_date ship_date       ship_mode  \
0         AG-2011-2040    1/1/2011  1/6/2011  Standard Class   
1        IN-2011-47883    1/1/2011  1/8/2011  Standard Class   
2         HU-2011-1220    1/1/2011  1/5/2011    Second Class   
3      IT-2011-3647632    1/1/2011  1/5/2011    Second Class   
4        IN-2011-47883    1/1/2011  1/8/2011  Standard Class   
...                ...         ...       ...             ...   
51285   CA-2014-115427  12/31/2014  1/4/2015  Standard Class   
51286     MO-2014-2560  12/31/2014  1/5/2015  Standard Class   
51287   MX-2014-110527  12/31/2014  1/2/2015    Second Class   
51288   MX-2014-114783  12/31/2014  1/6/2015  Standard Class   
51289   CA-2014-156720  12/31/2014  1/4/2015  Standard Class   

          customer_name      segment             state        country  market  \
0       Toby Braunhardt     Consumer       Constantine        Algeria  Africa   
1           Joseph Holt     Consumer   New South Wales      Australia    APAC   
2         Annie Thurman     Consumer          Budapest        Hungary    EMEA   
3          Eugene Moren  Home Office         Stockholm         Sweden      EU   
4           Joseph Holt     Consumer   New South Wales      Australia    APAC   
...                 ...          ...               ...            ...     ...   
51285        Erica Bern    Corporate        California  United States      US   
51286         Liz Preis     Consumer  Souss-Massa-Draƒ        Morocco  Africa   
51287  Charlotte Melton     Consumer           Managua      Nicaragua   LATAM   
51288     Tamara Dahlen     Consumer         Chihuahua         Mexico   LATAM   
51289     Jill Matthias     Consumer          Colorado  United States      US   

        region  ...         category sub_category  \
0       Africa  ...  Office Supplies      Storage   
1      Oceania  ...  Office Supplies     Supplies   
2         EMEA  ...  Office Supplies      Storage   
3        North  ...  Office Supplies        Paper   
4      Oceania  ...        Furniture  Furnishings   
...        ...  ...              ...          ...   
51285     West  ...  Office Supplies      Binders   
51286   Africa  ...  Office Supplies      Binders   
51287  Central  ...  Office Supplies       Labels   
51288    North  ...  Office Supplies       Labels   
51289     West  ...  Office Supplies    Fasteners   

                                          product_name sales quantity  \
0                                  Tenex Lockers, Blue   408        2   
1                             Acme Trimmer, High Speed   120        3   
2                              Tenex Box, Single Width    66        4   
3                          Enermax Note Cards, Premium    45        3   
4                           Eldon Light Bulb, Duo Pack   114        5   
...                                                ...   ...      ...   
51285  Cardinal Slant-D Ring Binder, Heavy Gauge Vinyl    14        2   
51286          Wilson Jones Hole Reinforcements, Clear     4        1   
51287           Hon Color Coded Labels, 5000 Label Set    26        3   
51288           Hon Legal Exhibit Labels, Alphabetical     7        1   
51289                              Bagged Rubber Bands     3        3   

       discount    profit  shipping_cost  order_priority  year  
0           0.0  106.1400          35.46          Medium  2011  
1           0.1   36.0360           9.72          Medium  2011  
2           0.0   29.6400           8.17            High  2011  
3           0.5  -26.0550           4.82            High  2011  
4           0.1   37.7700           4.70          Medium  2011  
...         ...       ...            ...             ...   ...  
51285       0.2    4.5188           0.89          Medium  2014  
51286       0.0    0.4200           0.49          Medium  2014  
51287       0.0   12.3600           0.35          Medium  2014  
51288       0.0    0.5600           0.20          Medium  2014  
51289       0.2   -0.6048           0.17   

In [111]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ...  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...   
3  Home Office        Stockholm     Sweden      EU    North  ...   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...   

          category sub_category                 product_name sales quantity  \
0  Office Supplies      Storage          Tenex Lockers, Blue   408        2   
1  Office Supplies     Supplies     Acme Trimmer, High Speed   120        3   
2  Office Supplies      Storage      Tenex Box, Single Width    66        4   
3  Office Supplies        Paper  Enermax Note Cards, Premium    45        3   
4        Furniture  Furnishings   Eldon Light Bulb, Duo Pack   114        5   

   discount   profit  shipping_cost  order_priority  year  
0       0.0  106.140          35.46          Medium  2011  
1       0.1   36.036           9.72          Medium  2011  
2       0.0   29.640           8.17            High  2011  
3       0.5  -26.055           4.82            High  2011  
4       0.1   37.770           4.70          Medium  2011  

[5 rows x 21 columns]

In [116]:
def profit_flag(a):
    if a >= 0:
        return 'positive'
    else:
        return 'negative'

In [117]:
profit_flag(-55)

'negative'

In [118]:
profit_flag(55)

'positive'

In [119]:
df_sales['flag_profit'] = df_sales['profit'].apply(profit_flag)

In [120]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ... sub_category  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...      Storage   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...     Supplies   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...      Storage   
3  Home Office        Stockholm     Sweden      EU    North  ...        Paper   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...  Furnishings   

                  product_name sales quantity discount   profit  \
0          Tenex Lockers, Blue   408        2      0.0  106.140   
1     Acme Trimmer, High Speed   120        3      0.1   36.036   
2      Tenex Box, Single Width    66        4      0.0   29.640   
3  Enermax Note Cards, Premium    45        3      0.5  -26.055   
4   Eldon Light Bulb, Duo Pack   114        5      0.1   37.770   

   shipping_cost  order_priority  year flag_profit  
0          35.46          Medium  2011    positive  
1           9.72          Medium  2011    positive  
2           8.17            High  2011    positive  
3           4.82            High  2011    negative  
4           4.70          Medium  2011    positive  

[5 rows x 22 columns]

In [121]:
df_sales['len_cust_name']=df_sales['customer_name'].apply(len)

In [122]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ...  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...   
3  Home Office        Stockholm     Sweden      EU    North  ...   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...   

                  product_name sales quantity discount   profit  \
0          Tenex Lockers, Blue   408        2      0.0  106.140   
1     Acme Trimmer, High Speed   120        3      0.1   36.036   
2      Tenex Box, Single Width    66        4      0.0   29.640   
3  Enermax Note Cards, Premium    45        3      0.5  -26.055   
4   Eldon Light Bulb, Duo Pack   114        5      0.1   37.770   

   shipping_cost  order_priority  year  flag_profit len_cust_name  
0          35.46          Medium  2011     positive            15  
1           9.72          Medium  2011     positive            11  
2           8.17            High  2011     positive            13  
3           4.82            High  2011     negative            12  
4           4.70          Medium  2011     positive            11  

[5 rows x 23 columns]

In [123]:
def quantity_flag(a):
    if a < 10:
        return 'low'
    elif a >10 and a <20:
        return 'medium'
    else:
        return 'high'

In [124]:
df_sales['flag_quantity']=df_sales['quantity'].apply(quantity_flag)

In [125]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ... sales  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...   408   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...   120   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...    66   
3  Home Office        Stockholm     Sweden      EU    North  ...    45   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...   114   

  quantity discount   profit shipping_cost  order_priority  year  flag_profit  \
0        2      0.0  106.140         35.46          Medium  2011     positive   
1        3      0.1   36.036          9.72          Medium  2011     positive   
2        4      0.0   29.640          8.17            High  2011     positive   
3        3      0.5  -26.055          4.82            High  2011     negative   
4        5      0.1   37.770          4.70          Medium  2011     positive   

   len_cust_name flag_quantity  
0             15           low  
1             11           low  
2             13           low  
3             12           low  
4             11           low  

[5 rows x 24 columns]

In [126]:
df_sales

order_id  order_date ship_date       ship_mode  \
0         AG-2011-2040    1/1/2011  1/6/2011  Standard Class   
1        IN-2011-47883    1/1/2011  1/8/2011  Standard Class   
2         HU-2011-1220    1/1/2011  1/5/2011    Second Class   
3      IT-2011-3647632    1/1/2011  1/5/2011    Second Class   
4        IN-2011-47883    1/1/2011  1/8/2011  Standard Class   
...                ...         ...       ...             ...   
51285   CA-2014-115427  12/31/2014  1/4/2015  Standard Class   
51286     MO-2014-2560  12/31/2014  1/5/2015  Standard Class   
51287   MX-2014-110527  12/31/2014  1/2/2015    Second Class   
51288   MX-2014-114783  12/31/2014  1/6/2015  Standard Class   
51289   CA-2014-156720  12/31/2014  1/4/2015  Standard Class   

          customer_name      segment             state        country  market  \
0       Toby Braunhardt     Consumer       Constantine        Algeria  Africa   
1           Joseph Holt     Consumer   New South Wales      Australia    APAC   
2         Annie Thurman     Consumer          Budapest        Hungary    EMEA   
3          Eugene Moren  Home Office         Stockholm         Sweden      EU   
4           Joseph Holt     Consumer   New South Wales      Australia    APAC   
...                 ...          ...               ...            ...     ...   
51285        Erica Bern    Corporate        California  United States      US   
51286         Liz Preis     Consumer  Souss-Massa-Draƒ        Morocco  Africa   
51287  Charlotte Melton     Consumer           Managua      Nicaragua   LATAM   
51288     Tamara Dahlen     Consumer         Chihuahua         Mexico   LATAM   
51289     Jill Matthias     Consumer          Colorado  United States      US   

        region  ... sales quantity discount    profit shipping_cost  \
0       Africa  ...   408        2      0.0  106.1400         35.46   
1      Oceania  ...   120        3      0.1   36.0360          9.72   
2         EMEA  ...    66        4      0.0   29.6400          8.17   
3        North  ...    45        3      0.5  -26.0550          4.82   
4      Oceania  ...   114        5      0.1   37.7700          4.70   
...        ...  ...   ...      ...      ...       ...           ...   
51285     West  ...    14        2      0.2    4.5188          0.89   
51286   Africa  ...     4        1      0.0    0.4200          0.49   
51287  Central  ...    26        3      0.0   12.3600          0.35   
51288    North  ...     7        1      0.0    0.5600          0.20   
51289     West  ...     3        3      0.2   -0.6048          0.17   

       order_priority  year  flag_profit  len_cust_name flag_quantity  
0              Medium  2011     positive             15           low  
1              Medium  2011     positive             11           low  
2                High  2011     positive             13           low  
3                High  2011     negative             12           low  
4              Medium  2011     positive             11           low  
...               ...   ...          ...            ...           ...  
51285          Medium  2014     positive             10           low  
51286          Medium  2014     positive              9           low  
51287          Medium  2014     positive             16           low  
51288          Medium  2014     positive             13           low  
51289          Medium  2014     negative             13           low  

[51290 rows x 24 columns]

In [127]:
df_sales['square_quantity']=df_sales['quantity'].apply(lambda a : a**2)

In [128]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ... quantity  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...        2   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...        3   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...        4   
3  Home Office        Stockholm     Sweden      EU    North  ...        3   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...        5   

  discount   profit shipping_cost order_priority  year  flag_profit  \
0      0.0  106.140         35.46         Medium  2011     positive   
1      0.1   36.036          9.72         Medium  2011     positive   
2      0.0   29.640          8.17           High  2011     positive   
3      0.5  -26.055          4.82           High  2011     negative   
4      0.1   37.770          4.70         Medium  2011     positive   

   len_cust_name  flag_quantity square_quantity  
0             15            low               4  
1             11            low               9  
2             13            low              16  
3             12            low               9  
4             11            low              25  

[5 rows x 25 columns]

In [129]:
import numpy as np

In [130]:
np.array([2,3,4,5,6])

array([2, 3, 4, 5, 6])

In [131]:
type(np.array([2,3,4,5,6]))

numpy.ndarray

In [132]:
np.array([[2,3,4],[4,5,6]])

array([[2, 3, 4],
       [4, 5, 6]])

In [135]:
np.array([[1,2,3,4],[2,3,4,5]])

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [136]:
l =[[1,2,3,4],[2,3,4,5]]

In [137]:
l

[[1, 2, 3, 4], [2, 3, 4, 5]]

In [138]:
l[0][0]

1

In [141]:
a = np.array([3,4,5,6])

In [142]:
a

array([3, 4, 5, 6])

In [143]:
a = np.array([3,4,5,6],ndmin = 5)

In [144]:
a

array([[[[[3, 4, 5, 6]]]]])

In [145]:
a = np.array([3,4,5,6],ndmin = 3)

In [147]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [148]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [149]:
arr.ndim

2

In [150]:
#Matrices are sub_class of array

In [154]:
np.random.randint(1,10,(4,4))

array([[3, 9, 7, 4],
       [8, 1, 9, 4],
       [8, 4, 9, 4],
       [7, 4, 9, 4]])

In [155]:
np.random.randint(1,10,(4,4,2))

array([[[3, 7],
        [3, 7],
        [2, 9],
        [7, 7]],

       [[6, 1],
        [4, 1],
        [6, 9],
        [5, 7]],

       [[1, 1],
        [8, 8],
        [1, 4],
        [2, 2]],

       [[9, 2],
        [5, 6],
        [3, 3],
        [1, 3]]])